import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_curve, auc
)

os.chdir(os.path.dirname(os.path.abspath(__file__)))


# ============================================
# 1. Locate and load each model's saved results.
# ============================================
RESULT_FILES = {
    'SVM': ['../svm/svm_severity_analysis.csv'],
    'LSTM': ['../lstm/lstm_severity_analysis.csv'],
    'Naive Bayes': [
        '../nb/nb_severity_analysis.csv',
        '../nb/severity_breakdown_results.csv',
        '../naive_bayes/nb_severity_analysis.csv',
        '../naive_bayes/severity_breakdown_results.csv',
    ],
}

REQUIRED_COLUMNS = {
    'true_label', 'predicted_label', 'severity_level',
    'had_personal_target', 'intensity_bucket', 'correct'
}


def _find_existing(paths):
    for p in paths:
        if os.path.exists(p):
            return p
    return None


results = {}
missing = []
for model_name, candidate_paths in RESULT_FILES.items():
    found_path = _find_existing(candidate_paths)
    if found_path is None:
        missing.append((model_name, candidate_paths))
        continue
    df = pd.read_csv(found_path)
    missing_cols = REQUIRED_COLUMNS - set(df.columns)
    if missing_cols:
        raise ValueError(
            f"{found_path} is missing expected columns {missing_cols}. "
            f"Was it generated by an older version of the model script?"
        )
    results[model_name] = df
    print(f"Loaded {model_name} results from {found_path} ({len(df)} rows)")

if missing:
    missing_desc = "; ".join(
        f"{name} (looked for {' or '.join(paths)})" for name, paths in missing
    )
    raise FileNotFoundError(
        f"Missing result file(s) for: {missing_desc}. "
        "Run the corresponding model script at least once before this "
        "comparison script."
    )

sizes = {name: len(df) for name, df in results.items()}
if len(set(sizes.values())) > 1:
    print(f"[WARNING] Test set sizes differ across models: {sizes}. "
          "Comparisons below are still valid per-model, but the models "
          "may not have been evaluated on identical test sets.")

HAS_CONFIDENCE = all('confidence_score' in df.columns for df in results.values())
if not HAS_CONFIDENCE:
    missing_conf = [name for name, df in results.items() if 'confidence_score' not in df.columns]
    print(f"\n[NOTE] 'confidence_score' column missing for: {missing_conf}. "
          "Section 6 (ROC-AUC curves) will be skipped. To enable it, add "
          "a confidence_score column (the model's final adjusted "
          "probability) to the comparison DataFrame in the corresponding "
          "model script(s) and re-run them.")


# ============================================
# 2. Overall metrics per model.
# ============================================
overall_rows = []
for model_name, df in results.items():
    y_true = df['true_label']
    y_pred = df['predicted_label']
    overall_rows.append({
        'model': model_name,
        'accuracy': accuracy_score(y_true, y_pred),
        'precision': precision_score(y_true, y_pred, zero_division=0),
        'recall': recall_score(y_true, y_pred, zero_division=0),
        'f1': f1_score(y_true, y_pred, zero_division=0),
    })

overall_df = pd.DataFrame(overall_rows).set_index('model')
overall_df = overall_df.loc[['SVM', 'LSTM', 'Naive Bayes']]  # fixed, readable order

print("\n===== Overall metrics =====")
print(overall_df.round(4))
overall_df.round(4).to_csv('model_comparison_overall.csv')
print("Saved model_comparison_overall.csv")


# ============================================
# 3. Breakdown tables: accuracy by severity level / personal target /
# intensity bucket, one column per model.
# ============================================
def accuracy_breakdown(group_col):
    frames = []
    for model_name, df in results.items():
        acc = df.groupby(group_col, observed=True)['correct'].mean()
        acc.name = model_name
        frames.append(acc)
    return pd.concat(frames, axis=1)


by_severity = accuracy_breakdown('severity_level')
by_target = accuracy_breakdown('had_personal_target')
by_intensity = accuracy_breakdown('intensity_bucket')

print("\n===== Accuracy by severity level =====")
print(by_severity.round(4))
print("\n===== Accuracy by personal-target presence =====")
print(by_target.round(4))
print("\n===== Accuracy by intensity bucket =====")
print(by_intensity.round(4))

by_severity.round(4).to_csv('model_comparison_by_severity.csv')
by_target.round(4).to_csv('model_comparison_by_target.csv')
by_intensity.round(4).to_csv('model_comparison_by_intensity.csv')
print("\nSaved model_comparison_by_severity.csv, "
      "model_comparison_by_target.csv, model_comparison_by_intensity.csv")


# ============================================
# 4. Charts (grouped bars, one group per category, one bar per model).
# ============================================
MODEL_COLORS = {'SVM': '#4C72B0', 'LSTM': '#DD8452', 'Naive Bayes': '#55A868'}


def grouped_bar_chart(data, title, ylabel, filename, ylim=None):
    fig, ax = plt.subplots(figsize=(10, 5.5))
    data.plot(kind='bar', ax=ax, color=[MODEL_COLORS[c] for c in data.columns])
    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xlabel('')
    if ylim:
        ax.set_ylim(*ylim)
    ax.legend(title='Model', loc='center left', bbox_to_anchor=(1.0, 0.5))
    plt.xticks(rotation=20, ha='right')
    plt.tight_layout()
    plt.savefig(filename, bbox_inches='tight', dpi=150)
    plt.show()
    print(f"Saved {filename}")


grouped_bar_chart(
    overall_df[['accuracy', 'precision', 'recall', 'f1']].T,
    'Overall Metrics by Model', 'Score', 'model_comparison_overall.png',
    ylim=(0, 1)
)
grouped_bar_chart(
    overall_df[['precision', 'recall']].T,
    'Precision vs Recall by Model', 'Score', 'model_comparison_precision_recall.png',
    ylim=(0, 1)
)
grouped_bar_chart(
    by_severity, 'Accuracy by Severity Level', 'Accuracy',
    'model_comparison_by_severity.png', ylim=(0, 1)
)
grouped_bar_chart(
    by_target, 'Accuracy by Personal-Target Presence', 'Accuracy',
    'model_comparison_by_target.png', ylim=(0, 1)
)
grouped_bar_chart(
    by_intensity, 'Accuracy by Intensity Bucket', 'Accuracy',
    'model_comparison_by_intensity.png', ylim=(0, 1)
)


model_names = ['SVM', 'LSTM', 'Naive Bayes']


# ============================================
# 5. ROC-AUC curves
# ============================================
if HAS_CONFIDENCE:
    print("\n===== ROC-AUC =====")
    fig, ax = plt.subplots(figsize=(7, 7))
    auc_scores = {}
    for model_name in model_names:
        df = results[model_name]
        fpr, tpr, _ = roc_curve(df['true_label'], df['confidence_score'])
        model_auc = auc(fpr, tpr)
        auc_scores[model_name] = model_auc
        ax.plot(fpr, tpr, label=f'{model_name} (AUC = {model_auc:.3f})',
                color=MODEL_COLORS[model_name], linewidth=2)
        print(f"{model_name}: AUC = {model_auc:.4f}")

    ax.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random (AUC = 0.500)')
    ax.set_xlabel('False Positive Rate')
    ax.set_ylabel('True Positive Rate')
    ax.set_title('ROC Curves by Model')
    ax.legend(loc='lower right')
    plt.tight_layout()
    plt.savefig('model_comparison_roc_auc.png', bbox_inches='tight', dpi=150)
    plt.show()
    print("Saved model_comparison_roc_auc.png")

    pd.Series(auc_scores, name='auc').round(4).to_csv('model_comparison_auc.csv')
    print("Saved model_comparison_auc.csv")
else:
    print("\n===== ROC-AUC =====")
    print("Skipped -- 'confidence_score' column not present in all three "
          "result files. See the NOTE printed near the top of this run.")


# ============================================
# 6. Bootstrap confidence intervals for accuracy and F1
# ============================================
def bootstrap_ci(y_true, y_pred, metric_fn, n_bootstrap=1000, ci=0.95, random_state=42):
    rng = np.random.RandomState(random_state)
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    n = len(y_true)
    scores = np.empty(n_bootstrap)
    for b in range(n_bootstrap):
        idx = rng.randint(0, n, n)
        scores[b] = metric_fn(y_true[idx], y_pred[idx])
    lower = np.percentile(scores, (1 - ci) / 2 * 100)
    upper = np.percentile(scores, (1 + ci) / 2 * 100)
    return scores.mean(), lower, upper


print("\n===== Bootstrap 95% Confidence Intervals (n=1000 resamples) =====")
bootstrap_rows = []
for model_name in model_names:
    df = results[model_name]
    y_true = df['true_label']
    y_pred = df['predicted_label']

    acc_mean, acc_lo, acc_hi = bootstrap_ci(
        y_true, y_pred, accuracy_score
    )
    f1_mean, f1_lo, f1_hi = bootstrap_ci(
        y_true, y_pred, lambda a, b: f1_score(a, b, zero_division=0)
    )

    print(f"{model_name}: "
          f"accuracy = {acc_mean:.4f} [{acc_lo:.4f}, {acc_hi:.4f}], "
          f"F1 = {f1_mean:.4f} [{f1_lo:.4f}, {f1_hi:.4f}]")
    bootstrap_rows.append({
        'model': model_name,
        'accuracy_mean': acc_mean, 'accuracy_ci_lower': acc_lo, 'accuracy_ci_upper': acc_hi,
        'f1_mean': f1_mean, 'f1_ci_lower': f1_lo, 'f1_ci_upper': f1_hi,
    })

bootstrap_df = pd.DataFrame(bootstrap_rows).set_index('model')
bootstrap_df.round(4).to_csv('model_comparison_bootstrap_ci.csv')
print("Saved model_comparison_bootstrap_ci.csv")

# Visualise as error-bar plot: accuracy per model with 95% CI whiskers.
fig, ax = plt.subplots(figsize=(7, 5))
x_pos = np.arange(len(model_names))
acc_means = [bootstrap_df.loc[m, 'accuracy_mean'] for m in model_names]
acc_errs_lower = [bootstrap_df.loc[m, 'accuracy_mean'] - bootstrap_df.loc[m, 'accuracy_ci_lower'] for m in model_names]
acc_errs_upper = [bootstrap_df.loc[m, 'accuracy_ci_upper'] - bootstrap_df.loc[m, 'accuracy_mean'] for m in model_names]
ax.bar(x_pos, acc_means, yerr=[acc_errs_lower, acc_errs_upper], capsize=8,
       color=[MODEL_COLORS[m] for m in model_names])
ax.set_xticks(x_pos)
ax.set_xticklabels(model_names)
ax.set_ylabel('Accuracy')
ax.set_ylim(0.7, 0.95)
ax.set_title('Accuracy with 95% Bootstrap Confidence Intervals')
plt.tight_layout()
plt.savefig('model_comparison_bootstrap_ci.png', bbox_inches='tight', dpi=150)
plt.show()
print("Saved model_comparison_bootstrap_ci.png")


print("\nDone. All comparison tables/charts saved to the current directory.")